# Generated by Django 2.2.6 on 2019-10-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('age', models.CharField(max_length=10, verbose_name='年龄')),
                ('gender', models.CharField(choices=[('male', '男'), ('femal', '女')], max_length=10, verbose_name='性别')),
                ('is_deleted', models.BooleanField(default=False)),
                ('introduce', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
