# Generated by Django 2.2.6 on 2019-10-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191028_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', '女'), ('male', '男')], default='male', max_length=10, verbose_name='性别'),
        ),
    ]
