# Generated by Django 2.2.6 on 2019-10-28 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191028_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id'], 'verbose_name': '新闻列表', 'verbose_name_plural': '新闻'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
